os:
  - linux
  - osx

env:
  - CMAKE_PREFIX_PATH=/usr/local/opt/qt4

language: c
compiler:
  - gcc
  - clang

sudo: required
dist: trusty

before_install:
  - ./.travis-deps.sh

script: mkdir build && cd build && cmake .. && make
